# Generated by Django 4.2.5 on 2023-09-18 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProj', '0003_modifiers_rename_indicators_baseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseline',
            name='id',
        ),
        migrations.AlterField(
            model_name='baseline',
            name='disease',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='FirstProj.disease'),
        ),
    ]
